#!/bin/bash

sudo mysql -u root <<QUERY

CREATE DATABASE test;
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';
FLUSH PRIVILEGES;
USE test;

CREATE TABLE user (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  login VARCHAR(50) NOT NULL,
  password VARCHAR(50) NOT NULL,

  PRIMARY KEY (id)
);

CREATE TABLE song (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  author VARCHAR(50) NOT NULL,
  genre VARCHAR(50) NOT NULL,
  duration MEDIUMINT UNSIGNED NOT NULL,
  date DATE NOT NULL,

  PRIMARY KEY (id)
);

CREATE TABLE like_dislike (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id MEDIUMINT UNSIGNED NOT NULL,
  song_id MEDIUMINT UNSIGNED NOT NULL,
  value BOOL,

  PRIMARY KEY (id),

  FOREIGN KEY (user_id)
    REFERENCES user(id)
    ON DELETE CASCADE,

  FOREIGN KEY (song_id)
    REFERENCES song(id)
    ON DELETE CASCADE
);

CREATE TABLE listen (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id MEDIUMINT UNSIGNED NOT NULL,
  song_id MEDIUMINT UNSIGNED NOT NULL,
  count MEDIUMINT UNSIGNED NOT NULL,

  PRIMARY KEY (id),

  FOREIGN KEY (user_id)
    REFERENCES user(id)
    ON DELETE CASCADE,

  FOREIGN KEY (song_id)
    REFERENCES song(id)
    ON DELETE CASCADE
);

CREATE TABLE session (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  session VARCHAR(65) NOT NULL,
  login VARCHAR(50) NOT NULL,

  PRIMARY KEY (id),

  FOREIGN KEY (login)
    REFERENCES user(login)
    ON DELETE CASCADE
);

CREATE TABLE recommendation (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id MEDIUMINT UNSIGNED NOT NULL,
  song_id MEDIUMINT UNSIGNED NOT NULL,

  PRIMARY KEY (id),

  FOREIGN KEY (user_id)
    REFERENCES user(id)
    ON DELETE CASCADE,

  FOREIGN KEY (song_id)
    REFERENCES song(id)
    ON DELETE CASCADE
);

QUERY
